name: GitHub Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MY_HOST: "127.0.0.1"
  COMPANY_NAME: "CCT"

jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      FULLNAME: "Mary Doe"
    steps:
      - run: echo ${{ env.COMPANY_NAME }}
      - run: echo "My host is $MY_HOST and $FULLNAME"
      - run: echo "Hello ${{ github.actor }} $FULLNAME $COMPANY_NAME"

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - run: echo "Repo ${{ github.repository }} ${{ env.MY_HOST }}"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "deploy job to production server ${{ job.status }}"
